/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TerminosRouteImport } from './routes/terminos'
import { Route as PrivacidadRouteImport } from './routes/privacidad'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TiendaSlugRouteImport } from './routes/tienda.$slug'
import { Route as AppWhatsappRouteImport } from './routes/_app.whatsapp'
import { Route as AppRecetasRouteImport } from './routes/_app.recetas'
import { Route as AppPublicarRouteImport } from './routes/_app.publicar'
import { Route as AppProductosRouteImport } from './routes/_app.productos'
import { Route as AppInteligenciaRouteImport } from './routes/_app.inteligencia'
import { Route as AppExperimentosRouteImport } from './routes/_app.experimentos'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppConfiguracionRouteImport } from './routes/_app.configuracion'
import { Route as AppCoachRouteImport } from './routes/_app.coach'
import { Route as AppCalendarioRouteImport } from './routes/_app.calendario'
import { Route as AppBibliotecaRouteImport } from './routes/_app.biblioteca'
import { Route as AppBandejaRouteImport } from './routes/_app.bandeja'
import { Route as AppAutomatizacionesRouteImport } from './routes/_app.automatizaciones'
import { Route as AppAnunciosRouteImport } from './routes/_app.anuncios'
import { Route as AppAnaliticasRouteImport } from './routes/_app.analiticas'
import { Route as OauthCallbackProviderRouteImport } from './routes/oauth.callback.$provider'

const TerminosRoute = TerminosRouteImport.update({
  id: '/terminos',
  path: '/terminos',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadRoute = PrivacidadRouteImport.update({
  id: '/privacidad',
  path: '/privacidad',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TiendaSlugRoute = TiendaSlugRouteImport.update({
  id: '/tienda/$slug',
  path: '/tienda/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWhatsappRoute = AppWhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => AppRoute,
} as any)
const AppRecetasRoute = AppRecetasRouteImport.update({
  id: '/recetas',
  path: '/recetas',
  getParentRoute: () => AppRoute,
} as any)
const AppPublicarRoute = AppPublicarRouteImport.update({
  id: '/publicar',
  path: '/publicar',
  getParentRoute: () => AppRoute,
} as any)
const AppProductosRoute = AppProductosRouteImport.update({
  id: '/productos',
  path: '/productos',
  getParentRoute: () => AppRoute,
} as any)
const AppInteligenciaRoute = AppInteligenciaRouteImport.update({
  id: '/inteligencia',
  path: '/inteligencia',
  getParentRoute: () => AppRoute,
} as any)
const AppExperimentosRoute = AppExperimentosRouteImport.update({
  id: '/experimentos',
  path: '/experimentos',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppConfiguracionRoute = AppConfiguracionRouteImport.update({
  id: '/configuracion',
  path: '/configuracion',
  getParentRoute: () => AppRoute,
} as any)
const AppCoachRoute = AppCoachRouteImport.update({
  id: '/coach',
  path: '/coach',
  getParentRoute: () => AppRoute,
} as any)
const AppCalendarioRoute = AppCalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => AppRoute,
} as any)
const AppBibliotecaRoute = AppBibliotecaRouteImport.update({
  id: '/biblioteca',
  path: '/biblioteca',
  getParentRoute: () => AppRoute,
} as any)
const AppBandejaRoute = AppBandejaRouteImport.update({
  id: '/bandeja',
  path: '/bandeja',
  getParentRoute: () => AppRoute,
} as any)
const AppAutomatizacionesRoute = AppAutomatizacionesRouteImport.update({
  id: '/automatizaciones',
  path: '/automatizaciones',
  getParentRoute: () => AppRoute,
} as any)
const AppAnunciosRoute = AppAnunciosRouteImport.update({
  id: '/anuncios',
  path: '/anuncios',
  getParentRoute: () => AppRoute,
} as any)
const AppAnaliticasRoute = AppAnaliticasRouteImport.update({
  id: '/analiticas',
  path: '/analiticas',
  getParentRoute: () => AppRoute,
} as any)
const OauthCallbackProviderRoute = OauthCallbackProviderRouteImport.update({
  id: '/oauth/callback/$provider',
  path: '/oauth/callback/$provider',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/privacidad': typeof PrivacidadRoute
  '/terminos': typeof TerminosRoute
  '/analiticas': typeof AppAnaliticasRoute
  '/anuncios': typeof AppAnunciosRoute
  '/automatizaciones': typeof AppAutomatizacionesRoute
  '/bandeja': typeof AppBandejaRoute
  '/biblioteca': typeof AppBibliotecaRoute
  '/calendario': typeof AppCalendarioRoute
  '/coach': typeof AppCoachRoute
  '/configuracion': typeof AppConfiguracionRoute
  '/dashboard': typeof AppDashboardRoute
  '/experimentos': typeof AppExperimentosRoute
  '/inteligencia': typeof AppInteligenciaRoute
  '/productos': typeof AppProductosRoute
  '/publicar': typeof AppPublicarRoute
  '/recetas': typeof AppRecetasRoute
  '/whatsapp': typeof AppWhatsappRoute
  '/tienda/$slug': typeof TiendaSlugRoute
  '/oauth/callback/$provider': typeof OauthCallbackProviderRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/privacidad': typeof PrivacidadRoute
  '/terminos': typeof TerminosRoute
  '/analiticas': typeof AppAnaliticasRoute
  '/anuncios': typeof AppAnunciosRoute
  '/automatizaciones': typeof AppAutomatizacionesRoute
  '/bandeja': typeof AppBandejaRoute
  '/biblioteca': typeof AppBibliotecaRoute
  '/calendario': typeof AppCalendarioRoute
  '/coach': typeof AppCoachRoute
  '/configuracion': typeof AppConfiguracionRoute
  '/dashboard': typeof AppDashboardRoute
  '/experimentos': typeof AppExperimentosRoute
  '/inteligencia': typeof AppInteligenciaRoute
  '/productos': typeof AppProductosRoute
  '/publicar': typeof AppPublicarRoute
  '/recetas': typeof AppRecetasRoute
  '/whatsapp': typeof AppWhatsappRoute
  '/tienda/$slug': typeof TiendaSlugRoute
  '/oauth/callback/$provider': typeof OauthCallbackProviderRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/privacidad': typeof PrivacidadRoute
  '/terminos': typeof TerminosRoute
  '/_app/analiticas': typeof AppAnaliticasRoute
  '/_app/anuncios': typeof AppAnunciosRoute
  '/_app/automatizaciones': typeof AppAutomatizacionesRoute
  '/_app/bandeja': typeof AppBandejaRoute
  '/_app/biblioteca': typeof AppBibliotecaRoute
  '/_app/calendario': typeof AppCalendarioRoute
  '/_app/coach': typeof AppCoachRoute
  '/_app/configuracion': typeof AppConfiguracionRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/experimentos': typeof AppExperimentosRoute
  '/_app/inteligencia': typeof AppInteligenciaRoute
  '/_app/productos': typeof AppProductosRoute
  '/_app/publicar': typeof AppPublicarRoute
  '/_app/recetas': typeof AppRecetasRoute
  '/_app/whatsapp': typeof AppWhatsappRoute
  '/tienda/$slug': typeof TiendaSlugRoute
  '/oauth/callback/$provider': typeof OauthCallbackProviderRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/privacidad'
    | '/terminos'
    | '/analiticas'
    | '/anuncios'
    | '/automatizaciones'
    | '/bandeja'
    | '/biblioteca'
    | '/calendario'
    | '/coach'
    | '/configuracion'
    | '/dashboard'
    | '/experimentos'
    | '/inteligencia'
    | '/productos'
    | '/publicar'
    | '/recetas'
    | '/whatsapp'
    | '/tienda/$slug'
    | '/oauth/callback/$provider'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/privacidad'
    | '/terminos'
    | '/analiticas'
    | '/anuncios'
    | '/automatizaciones'
    | '/bandeja'
    | '/biblioteca'
    | '/calendario'
    | '/coach'
    | '/configuracion'
    | '/dashboard'
    | '/experimentos'
    | '/inteligencia'
    | '/productos'
    | '/publicar'
    | '/recetas'
    | '/whatsapp'
    | '/tienda/$slug'
    | '/oauth/callback/$provider'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/auth'
    | '/onboarding'
    | '/privacidad'
    | '/terminos'
    | '/_app/analiticas'
    | '/_app/anuncios'
    | '/_app/automatizaciones'
    | '/_app/bandeja'
    | '/_app/biblioteca'
    | '/_app/calendario'
    | '/_app/coach'
    | '/_app/configuracion'
    | '/_app/dashboard'
    | '/_app/experimentos'
    | '/_app/inteligencia'
    | '/_app/productos'
    | '/_app/publicar'
    | '/_app/recetas'
    | '/_app/whatsapp'
    | '/tienda/$slug'
    | '/oauth/callback/$provider'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  OnboardingRoute: typeof OnboardingRoute
  PrivacidadRoute: typeof PrivacidadRoute
  TerminosRoute: typeof TerminosRoute
  TiendaSlugRoute: typeof TiendaSlugRoute
  OauthCallbackProviderRoute: typeof OauthCallbackProviderRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terminos': {
      id: '/terminos'
      path: '/terminos'
      fullPath: '/terminos'
      preLoaderRoute: typeof TerminosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidad': {
      id: '/privacidad'
      path: '/privacidad'
      fullPath: '/privacidad'
      preLoaderRoute: typeof PrivacidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tienda/$slug': {
      id: '/tienda/$slug'
      path: '/tienda/$slug'
      fullPath: '/tienda/$slug'
      preLoaderRoute: typeof TiendaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/whatsapp': {
      id: '/_app/whatsapp'
      path: '/whatsapp'
      fullPath: '/whatsapp'
      preLoaderRoute: typeof AppWhatsappRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/recetas': {
      id: '/_app/recetas'
      path: '/recetas'
      fullPath: '/recetas'
      preLoaderRoute: typeof AppRecetasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/publicar': {
      id: '/_app/publicar'
      path: '/publicar'
      fullPath: '/publicar'
      preLoaderRoute: typeof AppPublicarRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/productos': {
      id: '/_app/productos'
      path: '/productos'
      fullPath: '/productos'
      preLoaderRoute: typeof AppProductosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inteligencia': {
      id: '/_app/inteligencia'
      path: '/inteligencia'
      fullPath: '/inteligencia'
      preLoaderRoute: typeof AppInteligenciaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/experimentos': {
      id: '/_app/experimentos'
      path: '/experimentos'
      fullPath: '/experimentos'
      preLoaderRoute: typeof AppExperimentosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/configuracion': {
      id: '/_app/configuracion'
      path: '/configuracion'
      fullPath: '/configuracion'
      preLoaderRoute: typeof AppConfiguracionRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/coach': {
      id: '/_app/coach'
      path: '/coach'
      fullPath: '/coach'
      preLoaderRoute: typeof AppCoachRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/calendario': {
      id: '/_app/calendario'
      path: '/calendario'
      fullPath: '/calendario'
      preLoaderRoute: typeof AppCalendarioRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/biblioteca': {
      id: '/_app/biblioteca'
      path: '/biblioteca'
      fullPath: '/biblioteca'
      preLoaderRoute: typeof AppBibliotecaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/bandeja': {
      id: '/_app/bandeja'
      path: '/bandeja'
      fullPath: '/bandeja'
      preLoaderRoute: typeof AppBandejaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/automatizaciones': {
      id: '/_app/automatizaciones'
      path: '/automatizaciones'
      fullPath: '/automatizaciones'
      preLoaderRoute: typeof AppAutomatizacionesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/anuncios': {
      id: '/_app/anuncios'
      path: '/anuncios'
      fullPath: '/anuncios'
      preLoaderRoute: typeof AppAnunciosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/analiticas': {
      id: '/_app/analiticas'
      path: '/analiticas'
      fullPath: '/analiticas'
      preLoaderRoute: typeof AppAnaliticasRouteImport
      parentRoute: typeof AppRoute
    }
    '/oauth/callback/$provider': {
      id: '/oauth/callback/$provider'
      path: '/oauth/callback/$provider'
      fullPath: '/oauth/callback/$provider'
      preLoaderRoute: typeof OauthCallbackProviderRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppAnaliticasRoute: typeof AppAnaliticasRoute
  AppAnunciosRoute: typeof AppAnunciosRoute
  AppAutomatizacionesRoute: typeof AppAutomatizacionesRoute
  AppBandejaRoute: typeof AppBandejaRoute
  AppBibliotecaRoute: typeof AppBibliotecaRoute
  AppCalendarioRoute: typeof AppCalendarioRoute
  AppCoachRoute: typeof AppCoachRoute
  AppConfiguracionRoute: typeof AppConfiguracionRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppExperimentosRoute: typeof AppExperimentosRoute
  AppInteligenciaRoute: typeof AppInteligenciaRoute
  AppProductosRoute: typeof AppProductosRoute
  AppPublicarRoute: typeof AppPublicarRoute
  AppRecetasRoute: typeof AppRecetasRoute
  AppWhatsappRoute: typeof AppWhatsappRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAnaliticasRoute: AppAnaliticasRoute,
  AppAnunciosRoute: AppAnunciosRoute,
  AppAutomatizacionesRoute: AppAutomatizacionesRoute,
  AppBandejaRoute: AppBandejaRoute,
  AppBibliotecaRoute: AppBibliotecaRoute,
  AppCalendarioRoute: AppCalendarioRoute,
  AppCoachRoute: AppCoachRoute,
  AppConfiguracionRoute: AppConfiguracionRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppExperimentosRoute: AppExperimentosRoute,
  AppInteligenciaRoute: AppInteligenciaRoute,
  AppProductosRoute: AppProductosRoute,
  AppPublicarRoute: AppPublicarRoute,
  AppRecetasRoute: AppRecetasRoute,
  AppWhatsappRoute: AppWhatsappRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  OnboardingRoute: OnboardingRoute,
  PrivacidadRoute: PrivacidadRoute,
  TerminosRoute: TerminosRoute,
  TiendaSlugRoute: TiendaSlugRoute,
  OauthCallbackProviderRoute: OauthCallbackProviderRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
